<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Postcategory;
class PostCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $postcategories = array(
  array('category_id' => '100','term_id' => '36'),
  array('category_id' => '110','term_id' => '36'),
  array('category_id' => '100','term_id' => '41'),
  array('category_id' => '111','term_id' => '41'),
  array('category_id' => '99','term_id' => '40'),
  array('category_id' => '108','term_id' => '40'),
  array('category_id' => '100','term_id' => '39'),
  array('category_id' => '109','term_id' => '39'),
  array('category_id' => '99','term_id' => '38'),
  array('category_id' => '100','term_id' => '38'),
  array('category_id' => '99','term_id' => '37'),
  array('category_id' => '100','term_id' => '37'),
  array('category_id' => '99','term_id' => '35'),
  array('category_id' => '100','term_id' => '35'),
  array('category_id' => '100','term_id' => '42'),
  array('category_id' => '111','term_id' => '42'),
  array('category_id' => '102','term_id' => '44'),
  array('category_id' => '106','term_id' => '45'),
  array('category_id' => '106','term_id' => '46'),
  array('category_id' => '108','term_id' => '46'),
  array('category_id' => '106','term_id' => '47'),
  array('category_id' => '108','term_id' => '47'),
  array('category_id' => '105','term_id' => '48'),
  array('category_id' => '101','term_id' => '49'),
  array('category_id' => '99','term_id' => '50'),
  array('category_id' => '108','term_id' => '50'),
  array('category_id' => '104','term_id' => '51'),
  array('category_id' => '109','term_id' => '51'),
  array('category_id' => '140','term_id' => '61'),
  array('category_id' => '138','term_id' => '61'),
  array('category_id' => '140','term_id' => '62'),
  array('category_id' => '138','term_id' => '62'),
  array('category_id' => '142','term_id' => '60'),
  array('category_id' => '136','term_id' => '60'),
  array('category_id' => '140','term_id' => '63'),
  array('category_id' => '137','term_id' => '63'),
  array('category_id' => '140','term_id' => '64'),
  array('category_id' => '140','term_id' => '65'),
  array('category_id' => '135','term_id' => '65'),
  array('category_id' => '141','term_id' => '66'),
  array('category_id' => '136','term_id' => '66'),
  array('category_id' => '141','term_id' => '67'),
  array('category_id' => '136','term_id' => '67'),
  array('category_id' => '141','term_id' => '68'),
  array('category_id' => '144','term_id' => '68'),
  array('category_id' => '138','term_id' => '68'),
  array('category_id' => '142','term_id' => '69'),
  array('category_id' => '144','term_id' => '69'),
  array('category_id' => '145','term_id' => '69'),
  array('category_id' => '138','term_id' => '69'),
  array('category_id' => '142','term_id' => '70'),
  array('category_id' => '144','term_id' => '70'),
  array('category_id' => '139','term_id' => '70'),
  array('category_id' => '143','term_id' => '71'),
  array('category_id' => '139','term_id' => '71'),
  array('category_id' => '142','term_id' => '72'),
  array('category_id' => '144','term_id' => '72'),
  array('category_id' => '138','term_id' => '72'),
  array('category_id' => '142','term_id' => '73'),
  array('category_id' => '144','term_id' => '73'),
  array('category_id' => '135','term_id' => '73'),
  array('category_id' => '142','term_id' => '74'),
  array('category_id' => '145','term_id' => '74'),
  array('category_id' => '137','term_id' => '74'),
  array('category_id' => '205','term_id' => '82'),
  array('category_id' => '197','term_id' => '82'),
  array('category_id' => '205','term_id' => '83'),
  array('category_id' => '209','term_id' => '83'),
  array('category_id' => '197','term_id' => '83'),
  array('category_id' => '206','term_id' => '84'),
  array('category_id' => '208','term_id' => '84'),
  array('category_id' => '197','term_id' => '84'),
  array('category_id' => '205','term_id' => '85'),
  array('category_id' => '197','term_id' => '85'),
  array('category_id' => '205','term_id' => '86'),
  array('category_id' => '196','term_id' => '86'),
  array('category_id' => '205','term_id' => '87'),
  array('category_id' => '196','term_id' => '87'),
  array('category_id' => '205','term_id' => '88'),
  array('category_id' => '196','term_id' => '88'),
  array('category_id' => '205','term_id' => '90'),
  array('category_id' => '198','term_id' => '90'),
  array('category_id' => '205','term_id' => '91'),
  array('category_id' => '198','term_id' => '91'),
  array('category_id' => '205','term_id' => '92'),
  array('category_id' => '200','term_id' => '92'),
  array('category_id' => '205','term_id' => '93'),
  array('category_id' => '199','term_id' => '93'),
  array('category_id' => '205','term_id' => '81'),
  array('category_id' => '196','term_id' => '81'),
  array('category_id' => '205','term_id' => '89'),
  array('category_id' => '198','term_id' => '89'),
  array('category_id' => '224','term_id' => '96'),
  array('category_id' => '227','term_id' => '96'),
  array('category_id' => '224','term_id' => '97'),
  array('category_id' => '228','term_id' => '97'),
  array('category_id' => '224','term_id' => '98'),
  array('category_id' => '229','term_id' => '98'),
  array('category_id' => '224','term_id' => '99'),
  array('category_id' => '229','term_id' => '99'),
  array('category_id' => '224','term_id' => '100'),
  array('category_id' => '230','term_id' => '100'),
  array('category_id' => '223','term_id' => '101'),
  array('category_id' => '231','term_id' => '101'),
  array('category_id' => '223','term_id' => '102'),
  array('category_id' => '228','term_id' => '102'),
  array('category_id' => '223','term_id' => '103'),
  array('category_id' => '228','term_id' => '103'),
  array('category_id' => '223','term_id' => '104'),
  array('category_id' => '229','term_id' => '104'),
  array('category_id' => '223','term_id' => '105'),
  array('category_id' => '225','term_id' => '105'),
  array('category_id' => '223','term_id' => '106'),
  array('category_id' => '224','term_id' => '106'),
  array('category_id' => '225','term_id' => '106'),
  array('category_id' => '226','term_id' => '106'),
  array('category_id' => '228','term_id' => '106'),
  array('category_id' => '225','term_id' => '107'),
  array('category_id' => '227','term_id' => '107'),
  array('category_id' => '225','term_id' => '108'),
  array('category_id' => '228','term_id' => '108'),
  array('category_id' => '223','term_id' => '109'),
  array('category_id' => '228','term_id' => '109'),
  array('category_id' => '223','term_id' => '110'),
  array('category_id' => '224','term_id' => '110'),
  array('category_id' => '225','term_id' => '110'),
  array('category_id' => '229','term_id' => '110')
);
	
	Postcategory::insert($postcategories);
    }
}
