<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Postmedia;
class PostMediaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$postmedia = array(
  array('media_id' => '1','term_id' => '35'),
  array('media_id' => '2','term_id' => '35'),
  array('media_id' => '3','term_id' => '35'),
  array('media_id' => '4','term_id' => '35'),
  array('media_id' => '5','term_id' => '36'),
  array('media_id' => '6','term_id' => '36'),
  array('media_id' => '7','term_id' => '37'),
  array('media_id' => '8','term_id' => '37'),
  array('media_id' => '9','term_id' => '37'),
  array('media_id' => '10','term_id' => '38'),
  array('media_id' => '11','term_id' => '38'),
  array('media_id' => '12','term_id' => '39'),
  array('media_id' => '13','term_id' => '39'),
  array('media_id' => '14','term_id' => '40'),
  array('media_id' => '15','term_id' => '40'),
  array('media_id' => '16','term_id' => '41'),
  array('media_id' => '17','term_id' => '42'),
  array('media_id' => '18','term_id' => '42'),
  array('media_id' => '19','term_id' => '42'),
  array('media_id' => '20','term_id' => '44'),
  array('media_id' => '21','term_id' => '45'),
  array('media_id' => '22','term_id' => '45'),
  array('media_id' => '23','term_id' => '46'),
  array('media_id' => '24','term_id' => '47'),
  array('media_id' => '25','term_id' => '48'),
  array('media_id' => '26','term_id' => '48'),
  array('media_id' => '27','term_id' => '49'),
  array('media_id' => '28','term_id' => '49'),
  array('media_id' => '32','term_id' => '50'),
  array('media_id' => '33','term_id' => '50'),
  array('media_id' => '34','term_id' => '50'),
  array('media_id' => '35','term_id' => '51'),
  array('media_id' => '36','term_id' => '60'),
  array('media_id' => '37','term_id' => '60'),
  array('media_id' => '38','term_id' => '61'),
  array('media_id' => '39','term_id' => '61'),
  array('media_id' => '40','term_id' => '61'),
  array('media_id' => '41','term_id' => '61'),
  array('media_id' => '42','term_id' => '62'),
  array('media_id' => '43','term_id' => '62'),
  array('media_id' => '44','term_id' => '62'),
  array('media_id' => '45','term_id' => '63'),
  array('media_id' => '46','term_id' => '63'),
  array('media_id' => '47','term_id' => '63'),
  array('media_id' => '48','term_id' => '64'),
  array('media_id' => '49','term_id' => '64'),
  array('media_id' => '50','term_id' => '65'),
  array('media_id' => '51','term_id' => '66'),
  array('media_id' => '52','term_id' => '66'),
  array('media_id' => '53','term_id' => '66'),
  array('media_id' => '54','term_id' => '67'),
  array('media_id' => '55','term_id' => '67'),
  array('media_id' => '57','term_id' => '68'),
  array('media_id' => '58','term_id' => '68'),
  array('media_id' => '59','term_id' => '69'),
  array('media_id' => '60','term_id' => '70'),
  array('media_id' => '61','term_id' => '70'),
  array('media_id' => '62','term_id' => '71'),
  array('media_id' => '63','term_id' => '71'),
  array('media_id' => '64','term_id' => '71'),
  array('media_id' => '65','term_id' => '72'),
  array('media_id' => '66','term_id' => '72'),
  array('media_id' => '67','term_id' => '72'),
  array('media_id' => '68','term_id' => '73'),
  array('media_id' => '69','term_id' => '73'),
  array('media_id' => '70','term_id' => '73'),
  array('media_id' => '71','term_id' => '74'),
  array('media_id' => '72','term_id' => '74'),
  array('media_id' => '73','term_id' => '81'),
  array('media_id' => '74','term_id' => '81'),
  array('media_id' => '75','term_id' => '81'),
  array('media_id' => '76','term_id' => '82'),
  array('media_id' => '78','term_id' => '83'),
  array('media_id' => '79','term_id' => '83'),
  array('media_id' => '80','term_id' => '83'),
  array('media_id' => '81','term_id' => '83'),
  array('media_id' => '82','term_id' => '84'),
  array('media_id' => '83','term_id' => '84'),
  array('media_id' => '84','term_id' => '85'),
  array('media_id' => '85','term_id' => '86'),
  array('media_id' => '86','term_id' => '87'),
  array('media_id' => '87','term_id' => '87'),
  array('media_id' => '88','term_id' => '88'),
  array('media_id' => '89','term_id' => '88'),
  array('media_id' => '90','term_id' => '89'),
  array('media_id' => '91','term_id' => '89'),
  array('media_id' => '92','term_id' => '89'),
  array('media_id' => '93','term_id' => '90'),
  array('media_id' => '94','term_id' => '90'),
  array('media_id' => '96','term_id' => '91'),
  array('media_id' => '97','term_id' => '91'),
  array('media_id' => '98','term_id' => '92'),
  array('media_id' => '99','term_id' => '93'),
  array('media_id' => '100','term_id' => '93'),
  array('media_id' => '101','term_id' => '96'),
  array('media_id' => '102','term_id' => '97'),
  array('media_id' => '103','term_id' => '98'),
  array('media_id' => '104','term_id' => '98'),
  array('media_id' => '105','term_id' => '99'),
  array('media_id' => '106','term_id' => '99'),
  array('media_id' => '107','term_id' => '100'),
  array('media_id' => '108','term_id' => '100'),
  array('media_id' => '109','term_id' => '101'),
  array('media_id' => '110','term_id' => '101'),
  array('media_id' => '111','term_id' => '102'),
  array('media_id' => '112','term_id' => '103'),
  array('media_id' => '113','term_id' => '104'),
  array('media_id' => '114','term_id' => '105'),
  array('media_id' => '115','term_id' => '105'),
  array('media_id' => '116','term_id' => '106'),
  array('media_id' => '117','term_id' => '107'),
  array('media_id' => '118','term_id' => '107'),
  array('media_id' => '119','term_id' => '108'),
  array('media_id' => '120','term_id' => '109'),
  array('media_id' => '121','term_id' => '109'),
  array('media_id' => '122','term_id' => '110')
);

       Postmedia::insert($postmedia);
    }
}
